name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (Optional) Run workflow manually
  workflow_dispatch:
  # (Optional) Run workflow when pushing to main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: General stats
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: Azie88
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Africa/Nairobi
          filename: github-metrics.svg

      - name: Language stats
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: Azie88
          template: classic
          base: ""
          config_timezone: Africa/Nairobi
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          filename: github-languages.svg
